easy_admin:
    entities:
        Margenes:
            class: App\Entity\Margenes
            label: 'MÃ¡rgenes'
            list:
                title: "Listado de %%entity_label%%"
                fields:
                  - { property: 'nombre', label: 'Nombre' }
                  - { property: 'porcentaje', label: 'Porcentaje' }
                  - { property: 'predet', label: 'Predeterminado' }